name: Build and deploy blog
on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install hexo-cli -g
          npm install hexo-renderer-less
          npm install hexo-renderer-ejs

          # Generate HTML
          hexo clean
          hexo generate

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          CLEAN: true
          BRANCH: gh-pages
          FOLDER: public/
